### PR TITLE
Changed SayMore to use XLIFF for localization

### PR DESCRIPTION
**Pull request by tombogle**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/saymore/147)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 30 of 30 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/saymore/147)* status: all files reviewed, 2 unresolved discussions (waiting on @tombogle)

___
*[`DistFiles/.guidsForInstaller.xml` line 19 at r1](https://reviewable.io/reviews/sillsdev/saymore/147#-N2DkPwh1-Byxegg7TZb:-N2DkPwi5ZNM3TOc5Z_Q:b57aweb) ([raw file](https://github.com/sillsdev/saymore/blob/680c9d035002d9d20ae0e98ccb1750225ac0a3ac/DistFiles/.guidsForInstaller.xml#L19)):*
> ```XML
>   <File Id="ProgramDir.SayMore.ru.tmx" Guid="cc88d74e-ff31-42e4-aff7-6735a308bc6a" />
>   <File Id="ProgramDir.SayMore.tr.tmx" Guid="7248fbda-98cd-4c09-a5c2-7c79642dfe3a" />
>   <File Id="ProgramDir.SayMore.zh_Hans.tmx" Guid="97c9cb3d-4995-43ca-a914-742a04d6ab90" />
> ```

Any reason to leave these .tmx entries in?
___
*[`DistFiles/SayMore.es.xlf` line 9 at r1](https://reviewable.io/reviews/sillsdev/saymore/147#-N2Dkseq47LqqoSwZhxm:-N2Dkser8uA1RKoP89x9:b-k6wub8) ([raw file](https://github.com/sillsdev/saymore/blob/680c9d035002d9d20ae0e98ccb1750225ac0a3ac/DistFiles/SayMore.es.xlf#L9)):*
> ```XML
>         <target xml:lang="es-ES" state="translated">Alfa</target>
>         <note>ID: BuildType.Alpha</note>
>       </trans-unit>
> ```

I'm surprised none of these are "approved".
I thought L10nSharp didn't even use unapproved translations by default.

**Comment by tombogle** [comment]
*[`DistFiles/.guidsForInstaller.xml` line 19 at r1](https://reviewable.io/reviews/sillsdev/saymore/147#-N2DkPwh1-Byxegg7TZb:-N2Dm2LaEX8Lub-B8PXF:b-1mrhn7) ([raw file](https://github.com/sillsdev/saymore/blob/680c9d035002d9d20ae0e98ccb1750225ac0a3ac/DistFiles/.guidsForInstaller.xml#L19)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Any reason to leave these .tmx entries in?
</blockquote></details>

I wasn't sure. I don't know if it in some way could help when doing an upgrade. I thought it might somehow be vaguely useful historical information. Basically, the paranoid side of me was afraid to remove them and the lazy side of me didn't want to put up a fight.

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/saymore/147)* status: all files reviewed, 1 unresolved discussion (waiting on @tombogle)

___
*[`DistFiles/.guidsForInstaller.xml` line 19 at r1](https://reviewable.io/reviews/sillsdev/saymore/147#-N2DkPwh1-Byxegg7TZb:-N2DnfOf53qx0wSQN1zl:b6z4c71) ([raw file](https://github.com/sillsdev/saymore/blob/680c9d035002d9d20ae0e98ccb1750225ac0a3ac/DistFiles/.guidsForInstaller.xml#L19)):*
<details><summary><i>Previously, tombogle (Tom Bogle) wrote…</i></summary><blockquote>

I wasn't sure. I don't know if it in some way could help when doing an upgrade. I thought it might somehow be vaguely useful historical information. Basically, the paranoid side of me was afraid to remove them and the lazy side of me didn't want to put up a fight.
</blockquote></details>

haha. :+1:

**Comment by tombogle** [comment]
*[`DistFiles/SayMore.es.xlf` line 9 at r1](https://reviewable.io/reviews/sillsdev/saymore/147#-N2Dkseq47LqqoSwZhxm:-N2DmxvVAiZZy6kYz6vO:b-1jmtr4) ([raw file](https://github.com/sillsdev/saymore/blob/680c9d035002d9d20ae0e98ccb1750225ac0a3ac/DistFiles/SayMore.es.xlf#L9)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I'm surprised none of these are "approved".
I thought L10nSharp didn't even use unapproved translations by default.
</blockquote></details>

In TMX, I don't know if there was such a thing. It must (or else we're passing some flag), because they all show up in the UI. I know crowdin has an option to not to even download them if unapproved. I waffled over whether to add them as approved or not. I figured that since SayMore doesn't actually care and I don't necessarily consider myself the final authority on whether the strings are correct or not, I'd leave them unapproved and wait for the day when the final authority shows up.

**Review by andrew-polk — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/saymore/147)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tombogle)

**Pull request merged**
