### PR TITLE
Support additional file formats

### PR DESCRIPTION
**Pull request by tombogle**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/saymore/172)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/saymore/172)* status: all files reviewed, 11 unresolved discussions (waiting on @tombogle)

___
*[`src/SayMore/MediaUtils/MediaFileInfo.cs` line 204 at r1](https://reviewable.io/reviews/sillsdev/saymore/172#-NQkOtU24LiQ0yMXsf_Y:-NQkSLcj1eoNO8ranUx3:b4wwhgh) ([raw file](https://github.com/sillsdev/saymore/blob/f13346e02662948d991bc1b41b23d64d9ccb399c/src/SayMore/MediaUtils/MediaFileInfo.cs#L204)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I'm not sure that's what you meant to say.
At least, it doesn't fit into my personal vocabulary/grammar.
</blockquote></details>

Ignore the fact that Reviewable thinks I was trying to make a suggestion.

**Review by tombogle — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/saymore/172)* status: all files reviewed, 11 unresolved discussions (waiting on @andrew-polk)

___
*[`DistFiles/aboutBox.htm` line 51 at r1](https://reviewable.io/reviews/sillsdev/saymore/172#-NQkKYfU1CedVZB6eyOB:-NR4tkCOESvTMbJxTNMw:b-pn6xn9) ([raw file](https://github.com/sillsdev/saymore/blob/b1c2c536ffd8e45a6dd8c6843898d98c0a654d55/DistFiles/aboutBox.htm#L51)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Did you intend to remove MediaInfo from here? (even though you still include it)
</blockquote></details>

No, when I removed it from there, I was planning to jettison it.
___
*[`DistFiles/FFmpeg/ffprobe.exe` line  at r1](https://reviewable.io/reviews/sillsdev/saymore/172#-NQkKBIY20BlQRACAmsA:-NR4wa6eDGHdYHjbtVhE:b-awx18c) ([raw file](https://github.com/sillsdev/saymore/blob/f13346e02662948d991bc1b41b23d64d9ccb399c/DistFiles/FFmpeg/ffprobe.exe#L)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

This is a huge file. I guess you've thought through the implications of this.
FWIW, we have a stripped down version of ffmpeg we include in Bloom. Probably can do the same thing for ffprobe. Makes the installer much smaller. But does come with its complexities/issues.
(I also see that ffmpeg is getting much bigger.)
</blockquote></details>

Thanks for noticing. I didn't. I think the typical SayMore user isn't really worried too much about the impact of installing two 77 MB files. I don't have time for more complexities/issues.
___
*[`src/SayMore/SayMore.csproj` line 1058 at r1](https://reviewable.io/reviews/sillsdev/saymore/172#-NQkS9yNBVLKqzbBtKVg:-NR4xxwK5oiXrGuL8ia5:bdnemc1) ([raw file](https://github.com/sillsdev/saymore/blob/f13346e02662948d991bc1b41b23d64d9ccb399c/src/SayMore/SayMore.csproj#L1058)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Is this an accident?
</blockquote></details>

Looks like it. Good catch (though it was set to do not copy, so I guess it didn't do anything bad even though it couldn't be found).
___
*[`src/SayMore/MediaUtils/MediaFileInfo.cs` line 21 at r1](https://reviewable.io/reviews/sillsdev/saymore/172#-NQkObhADF_tOcHSRYqy:-NR5-0qB9dOuH-zx8PbB:b-mx89hp) ([raw file](https://github.com/sillsdev/saymore/blob/f13346e02662948d991bc1b41b23d64d9ccb399c/src/SayMore/MediaUtils/MediaFileInfo.cs#L21)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

In case you care...
Indentation is a mix of tabs and spaces...
</blockquote></details>

Finally got motivated to add an .editorconfig file
___
*[`src/SayMore/MediaUtils/MediaFileInfo.cs` line 152 at r1](https://reviewable.io/reviews/sillsdev/saymore/172#-NQkQ6wkC-86dlUPF8Bu:-NR5-Y3YEr175VV9B4g1:blr75we) ([raw file](https://github.com/sillsdev/saymore/blob/f13346e02662948d991bc1b41b23d64d9ccb399c/src/SayMore/MediaUtils/MediaFileInfo.cs#L152)):*
> if (silVideoInfo != null &&
Ideally, it should probably be implemented in SIL.Media.MediaInfo. For now, I'll add it as an extension method called IsMotionPicture :-) 
___
*[`src/SayMore/MediaUtils/MediaFileInfo.cs` line 204 at r1](https://reviewable.io/reviews/sillsdev/saymore/172#-NQkOtU24LiQ0yMXsf_Y:-NR51z1f1ZPm73vopFZM:b-8y2i1c) ([raw file](https://github.com/sillsdev/saymore/blob/f13346e02662948d991bc1b41b23d64d9ccb399c/src/SayMore/MediaUtils/MediaFileInfo.cs#L204)):*
>  I decided to keep it around in case
You just need to get some more want, my friend.
___
*[`src/SayMore/MediaUtils/MediaFileInfo.cs` line 304 at r1](https://reviewable.io/reviews/sillsdev/saymore/172#-NQkR-g58WlqlaYIJkCc:-NR54ZAPAEfCSGA7NyLi:bb6un1j) ([raw file](https://github.com/sillsdev/saymore/blob/f13346e02662948d991bc1b41b23d64d9ccb399c/src/SayMore/MediaUtils/MediaFileInfo.cs#L304)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

If not verbose, you add a bunch of stuff to show. I assume that means that verbose will display even more elsewhere?
Deserves a comment.

Also, I would consider moving the html-building logic to a separate method so the logic of `GetInfoAsHtml` stays really straightforward and clear.
</blockquote></details>

Done
___
*[`src/SayMore/Resources/MoreMediaInfoStyles.css` line 41 at r1](https://reviewable.io/reviews/sillsdev/saymore/172#-NQkM-6W5gKj7HKhPl3g:-NR54ov8CySeA7Qp01sb:bb6un1j) ([raw file](https://github.com/sillsdev/saymore/blob/f13346e02662948d991bc1b41b23d64d9ccb399c/src/SayMore/Resources/MoreMediaInfoStyles.css#L41)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

If you want, you can simplify to 
```
h3, h4 {
    padding: 0 15px 0 10px;
}
```

You could also consider
```
h3, h4, .fieldName {
    padding: 0 15px 0 10px;
}

.fieldName
{
	white-space:nowrap;
}

```
</blockquote></details>

Done
___
*[`src/SayMore/UI/ComponentEditors/MediaFileMoreInfoDlg.cs` line 61 at r1](https://reviewable.io/reviews/sillsdev/saymore/172#-NQkN9p0229gDw6VV4C0:-NR55Iti45Ap9mx-4IRu:b-5jp19w) ([raw file](https://github.com/sillsdev/saymore/blob/f13346e02662948d991bc1b41b23d64d9ccb399c/src/SayMore/UI/ComponentEditors/MediaFileMoreInfoDlg.cs#L61)):*
> pdateSourceLabelDisplay
Done
___
*[`src/SayMore/UI/ComponentEditors/MediaFileMoreInfoDlg.Designer.cs` line 229 at r1](https://reviewable.io/reviews/sillsdev/saymore/172#-NQkOCW62wgjbRFjs5Xk:-NR55RHB4USthupkCUlf:bb6un1j) ([raw file](https://github.com/sillsdev/saymore/blob/f13346e02662948d991bc1b41b23d64d9ccb399c/src/SayMore/UI/ComponentEditors/MediaFileMoreInfoDlg.Designer.cs#L229)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

`_lblSource`?
</blockquote></details>

Done
___
*[`src/SayMoreTests/SayMoreTests.csproj` line 383 at r1](https://reviewable.io/reviews/sillsdev/saymore/172#-NQkS4pU9Acgr96hGLpA:-NR55mZb7uXzTSJihPLh:bb3jnhm) ([raw file](https://github.com/sillsdev/saymore/blob/f13346e02662948d991bc1b41b23d64d9ccb399c/src/SayMoreTests/SayMoreTests.csproj#L383)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Is this an accident?
</blockquote></details>

So it seems. I'm guessing some tool did this, but I can't think how/why.

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 10 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/saymore/172)* status: all files reviewed, 3 unresolved discussions (waiting on @tombogle)

___
*[`src/SayMore/MediaUtils/MediaFileInfo.cs` line 204 at r1](https://reviewable.io/reviews/sillsdev/saymore/172#-NQkOtU24LiQ0yMXsf_Y:-NR59aG15GXwRkgrtQAa:b-nwpzox) ([raw file](https://github.com/sillsdev/saymore/blob/f13346e02662948d991bc1b41b23d64d9ccb399c/src/SayMore/MediaUtils/MediaFileInfo.cs#L204)):*
<details><summary><i>Previously, tombogle (Tom Bogle) wrote…</i></summary><blockquote>

>  I decided to keep it around in case
You just need to get some more want, my friend.
</blockquote></details>

Too true.
___
*[`src/SayMoreTests/SayMoreTests.csproj` line 383 at r1](https://reviewable.io/reviews/sillsdev/saymore/172#-NQkS4pU9Acgr96hGLpA:-NR5ALbjDWpzMp05-sbP:b-2rbrdh) ([raw file](https://github.com/sillsdev/saymore/blob/f13346e02662948d991bc1b41b23d64d9ccb399c/src/SayMoreTests/SayMoreTests.csproj#L383)):*
<details><summary><i>Previously, tombogle (Tom Bogle) wrote…</i></summary><blockquote>

So it seems. I'm guessing some tool did this, but I can't think how/why.
</blockquote></details>

I've seen packages add readme files. Likely that happened at one point and you deleted the file.

**Review by andrew-polk — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/saymore/172)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tombogle)

**Pull request merged**
