### PR TITLE
Added option to import Audacity labels into free translation

### PR DESCRIPTION
**Pull request by tombogle**
Requested here: https://community.software.sil.org/t/saymore-import-of-audacity-track-label-can-we-have-it-go-to-free-translation/7095/5

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/saymore/170)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/saymore/170)* status: all files reviewed, 1 unresolved discussion (waiting on @hatton and @tombogle)

___
*[`src/SayMore/Transcription/UI/ComponentEditors/StartAnnotatingEditor.Designer.cs` line 385 at r1](https://reviewable.io/reviews/sillsdev/saymore/170#-NM-fT5A3cO-7NfAN0wo:-NM-fT5A3cO-7NfAN0wp:b-d2qbba) ([raw file](https://github.com/sillsdev/saymore/blob/faaeb04c109633d68c97ebf176be53df0dfd9a17/src/SayMore/Transcription/UI/ComponentEditors/StartAnnotatingEditor.Designer.cs#L385)):*
> ```Smalltalk
> 			this._lblAudacityLabelTier.Size = new System.Drawing.Size(101, 13);
> 			this._lblAudacityLabelTier.TabIndex = 15;
> 			this._lblAudacityLabelTier.Text = "Import label text into";
> ```

I guess you're purposefully not localizing this?
Otherwise, LGTM

**Comment by tombogle** [comment]
*[`src/SayMore/Transcription/UI/ComponentEditors/StartAnnotatingEditor.Designer.cs` line 385 at r1](https://reviewable.io/reviews/sillsdev/saymore/170#-NM-fT5A3cO-7NfAN0wo:-NM0UrQf5hvoZhvQZVnu:bwxcrlb) ([raw file](https://github.com/sillsdev/saymore/blob/faaeb04c109633d68c97ebf176be53df0dfd9a17/src/SayMore/Transcription/UI/ComponentEditors/StartAnnotatingEditor.Designer.cs#L385)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I guess you're purposefully not localizing this?
Otherwise, LGTM
</blockquote></details>

No, it should be localizable. That's L10nSharpExtenders bizarre quirk of setting a control to NotLocalizable when you reset the ID to match the new name.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/saymore/170)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @hatton)

___
*[`DistFiles/SayMore.es.xlf` line 1 at r2](https://reviewable.io/reviews/sillsdev/saymore/170#-NM0sDgqCnaMPBPCYaAq:-NM0sDgqCnaMPBPCYaAr:b-gm3fnz) ([raw file](https://github.com/sillsdev/saymore/blob/8dd1231fc352409fd83916e7dba25acd29fab41c/DistFiles/SayMore.es.xlf#L1)):*
> ```XML
> <?xml version="1.0" encoding="utf-8"?>
> ```

I only (very) briefly skimmed through this file.
___
*[`DistFiles/SayMore.es.xlf` line 49 at r2](https://reviewable.io/reviews/sillsdev/saymore/170#-NM0rxOC6jjscRYDOxz1:-NM0rxOC6jjscRYDOxz2:b-g9xcfy) ([raw file](https://github.com/sillsdev/saymore/blob/a90e25c9f948265609d10c24b80a05ac223ad3af/DistFiles/SayMore.es.xlf#L49)):*
> ```XML
>         <source xml:lang="en">***This record had an ambiguous {0}, produced by a bug in an old version of SayMore. The date was "{1}". SayMore has attempted to interpret the date, but might have swapped the day and month. Please accept our apologies for this error. After you have fixed the date or confirmed that it is correct, please delete this message.</source>
>         <note>ID: CommonToMultipleViews.BindingHelper.AmbiguousDateNote</note>
>         <note>Text appended to the note for an element with an ambiguous date field value</note>
> ```

Looks like all these non-ID notes got lost. Maybe that doesn't matter since this is Spanish, not the source (English).

**Comment by tombogle** [comment]
*[`DistFiles/SayMore.es.xlf` line 49 at r2](https://reviewable.io/reviews/sillsdev/saymore/170#-NM0rxOC6jjscRYDOxz1:-NM9bocy6OFsd7-_SVEP:b781fh5) ([raw file](https://github.com/sillsdev/saymore/blob/a90e25c9f948265609d10c24b80a05ac223ad3af/DistFiles/SayMore.es.xlf#L49)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Looks like all these non-ID notes got lost. Maybe that doesn't matter since this is Spanish, not the source (English).
</blockquote></details>

Yeah, I found that puzzling. Apparently the export from Crowdin strips them out for some reason. I'm thinking this is maybe the first time I've pulled down the content from Crowdin and just accepted it en masse rather than cherry-picking the handful of new translations. It made for a much uglier diff, but I figured at some point I'd need to bite the bullet, lest I forever have to manually cull through the changes and only accept the ones I want. Since localization comments (about the parameters, etc.) still appear correctly in Crowdin, I can't think of any reason why we should need to have them in the localization files.

**Pull request merged**
