### PR TITLE
SP-2283: Upgraded to .Net Framework 4.6.2

### PR DESCRIPTION
**Pull request by tombogle**
4.6.1 no longer supported. Also upgraded L10nSharp and SIL DLLs (to latest beta).

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/saymore/164)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/saymore/164)* status: all files reviewed, 1 unresolved discussion (waiting on @tombogle)

___
*[`src/SayMore/SayMore.csproj` line 3 at r1](https://reviewable.io/reviews/sillsdev/saymore/164#-NI81COj4gf4eUHQnf8H:-NI81COj4gf4eUHQnf8I:b-fg6edf) ([raw file](https://github.com/sillsdev/saymore/blob/71cf733db55d427d906533e655a8e1fe4eb448b3/src/SayMore/SayMore.csproj#L3)):*
> ```XML
> <?xml version="1.0" encoding="utf-8"?>
> <Project ToolsVersion="14.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
>   <Import Project="..\..\packages\SIL.Windows.Forms.Keyboarding.11.0.0-beta0040\build\SIL.Windows.Forms.Keyboarding.props" Condition="Exists('..\..\packages\SIL.Windows.Forms.Keyboarding.11.0.0-beta0040\build\SIL.Windows.Forms.Keyboarding.props')" />
> ```

Is it expected that this import for Keyboarding got removed?

**Comment by tombogle** [comment]
*[`src/SayMore/SayMore.csproj` line 3 at r1](https://reviewable.io/reviews/sillsdev/saymore/164#-NI81COj4gf4eUHQnf8H:-NI8AZAMCk1pF9QPfktn:bsapzx4) ([raw file](https://github.com/sillsdev/saymore/blob/71cf733db55d427d906533e655a8e1fe4eb448b3/src/SayMore/SayMore.csproj#L3)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Is it expected that this import for Keyboarding got removed?
</blockquote></details>

Yes, inexplicably, VisualStudio replaced the existing one (11.0.0-beta0040) at this line and added another one at line 1293. (These changes were in the first commit). I don't know why the Import elements are not all together. It's possible that this is what is causing VS to mess things up.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/saymore/164)* status: all files reviewed, 1 unresolved discussion (waiting on @tombogle)

___
*[`src/SayMore/SayMore.csproj` line 3 at r1](https://reviewable.io/reviews/sillsdev/saymore/164#-NI81COj4gf4eUHQnf8H:-NI8DWJB83MC4Nh5Sqa8:b-itcb39) ([raw file](https://github.com/sillsdev/saymore/blob/71cf733db55d427d906533e655a8e1fe4eb448b3/src/SayMore/SayMore.csproj#L3)):*
<details><summary><i>Previously, tombogle (Tom Bogle) wrote…</i></summary><blockquote>

Yes, inexplicably, VisualStudio replaced the existing one (11.0.0-beta0040) at this line and added another one at line 1293. (These changes were in the first commit). I don't know why the Import elements are not all together. It's possible that this is what is causing VS to mess things up.
</blockquote></details>

1293 is Keyboarding.targets whereas this is Keyboarding.props

**Comment by tombogle** [comment]
*[`src/SayMore/SayMore.csproj` line 3 at r1](https://reviewable.io/reviews/sillsdev/saymore/164#-NI81COj4gf4eUHQnf8H:-NI8GKhf2dxznMBquhUN:b-2el9n3) ([raw file](https://github.com/sillsdev/saymore/blob/71cf733db55d427d906533e655a8e1fe4eb448b3/src/SayMore/SayMore.csproj#L3)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

1293 is Keyboarding.targets whereas this is Keyboarding.props
</blockquote></details>

Can't put nothin' past you...

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/saymore/164)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tombogle)

**Pull request merged**
